### ISSUE TITLE
Prepare Milestone Report 2

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#166]
### Description

Another milestone is successfully passed. Now, we need to prepare detailed summary of what we have done and what we have learned. Report must cover all required activites below:

### Required Activities

- [x] Summary of the project and its current status
- [x] URL to the GitHub code repository and the specific release tag
- [x] URL to the deployed application using Docker
- [x] Instructions for building and deploying the application using Docker
- [x] Internal links to the design diagrams (class, use case, sequence ; internal means
links to the wiki pages)
- [x] Internal links to the updated project plan (including RAM)
- [x] Links to meeting notes specifically pertaining to the practice application
- [x] Lessons learned from the evaluation of tools and processes used for team
management
- [x] Challenges encountered and strategies you used to address them

### Estimated Time

2 hours

### Deadline

03 May 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
We have prepared the Milestone 2 Report for wiki with @yasinbastug, you can find the wikipage for report [here](https://github.com/bounswe/bounswe2024group2/wiki/Milestone-2-Report)
