### ISSUE TITLE
Document Weekly Efforts [Halil Ibrahim Kasapoglu]

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#235]
### Description

Weekly efforts section in personal page for cmpe 451 is missing (Week 1 to Week 3). They should be documented in my personal page.

### Required Activities

- [ ] Document Week #1 Effort
- [ ] Document Week #2 Effort
- [ ] Document Week #3 Effort

### Estimated Time

1 hour

### Deadline

8 October 2024

### Reviewer

@danzio19

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Added week1 contributions [here](https://github.com/bounswe/bounswe2024group2/wiki/Halil-%C4%B0brahim-Kasapo%C4%9Flu-CMPE-451/577d72ccde9665c80cbd7cbc20e5cfa8072f63cc)

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Updated weeek2 contributions [here](https://github.com/bounswe/bounswe2024group2/wiki/Halil-%C4%B0brahim-Kasapo%C4%9Flu-CMPE-451/076473103e2ef1a3032b1a568ffcaafbf4e0ef19)
I will also update status by the end of week 2, and will be adding the task I reviewed later on

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Final version [here](https://github.com/bounswe/bounswe2024group2/wiki/Halil-%C4%B0brahim-Kasapo%C4%9Flu-CMPE-451/777cf7cf3e5e9084df029bd2b4d09ddfd6cd5257#-contributions). Closing the issue.
