### ISSUE TITLE
Create the First Draft of Project Plan

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#247]
### Description

A plan should be written to follow and conduct tasks efficiently. First choose an environment to create the project plan. Then, make the plan and add it to the wiki page. Possible environments are Project Libre and Github project roadmap.

### Required Activities

- [x] Choose the environment
- [x] Make the plan
- [x] Add plan to the wiki page

### Estimated Time

2 hours

### Deadline

25.10.2024

### Reviewer

@furkansenkal

**Comment by mahmutbugramert** [comment]
Started to create project plan in project roadmap. Deadline is postponed

**Comment by mahmutbugramert** [comment]
Project plan is created and uploaded to wiki. [Here](https://github.com/bounswe/bounswe2024group2/wiki/Project-Plan-CmpE451)

**Comment by mahmutbugramert** [comment]
Issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed the project plan. It looks fine, good work, closing the issue.
