### ISSUE TITLE
Update the Project Plan

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#432]
### Description

One of the deliverables of the Milestone 2 is the updated Project Plan. Previous plan should be updated. New plans should be made for the future. Wiki page should be updated. Finally, Project Plan should be linked to Milestone Report.

### Required Activities

- [ ] Update the Project Plan.
- [ ] Plan the future.
- [ ] Update wiki page
- [ ] Link Project Plan to Milestone 2 Report

### Estimated Time

2 hours

### Deadline

29.11.2024

### Reviewer

@furkansenkal

**Comment by furkansenkal** [comment]
I reviewed the Project Plan and it looks good. Thank you.
