### ISSUE TITLE
Create checklist for Primary Features

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#436]
### Description

This issue focuses on documenting the checklist item: Primary Features for the project. The checklist will outline key tasks, deliverables, and documentation required for the successful completion of this item. Once created, the checklist will be used to track progress and ensure all necessary steps are completed.

### Required Activities

- [x] Create a checklist outlining the key primary features.
- [x] Ensure each checklist item clearly defines the expected functionality.  
- [x] Document the checklist in the Lab8 Pull Request.

### Estimated Time

2 hours

### Deadline

03.12.2024

### Reviewer

@mahmutbugramert

**Comment by m-erkam** [comment]
We created the acceptance criterias based on our requirements. Also, we have clarified the functionalities required in our statements. Issue can be closed as completed.

**Comment by mahmutbugramert** [comment]
I viewed your work. It looks great. Thank you. I am closing the issue.
