### ISSUE TITLE
Create checklist for API and its Documentation

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#438]
### Description

This issue focuses on documenting the checklist item: API and its Documentation for the project. The checklist will outline key tasks, deliverables, and documentation required for the successful completion of this item. Once created, the checklist will be used to track progress and ensure all necessary steps are completed.

### Required Activities

- [x] Create a checklist for all API endpoints, including expected inputs and outputs.  
- [x] Include a section for documenting the API and providing usage examples.  
- [x] Document the checklist in the Lab8 Pull Request.

### Estimated Time

2 hours

### Deadline

03.12.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by oguzpancuk** [comment]
Waiting for a review from @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Looks good to me, closing the issue
