### ISSUE TITLE
Create checklist for Standard(s) Being Followed 

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#439]
### Description

This issue focuses on documenting the checklist item: Standard(s) Being Followed for the project. The checklist will outline key tasks, deliverables, and documentation required for the successful completion of this item. Once created, the checklist will be used to track progress and ensure all necessary steps are completed.

### Required Activities

- [x] Create a checklist of the standards to be followed (e.g., coding conventions, API design guidelines).  
- [x] Ensure the checklist includes references to external documentation if applicable.  
- [x] Document the checklist in the Lab8 Pull Request.

### Estimated Time

2 hours

### Deadline

03.12.2024

### Reviewer

@furkansenkal

**Comment by rukiyeaslan** [comment]
This issue is completed and the related comment in the lab8 branch [here](https://github.com/bounswe/bounswe2024group2/pull/434#issuecomment-2514582900). Issue is up for a review by @furkansenkal.
