### ISSUE TITLE
Create checklist for Testing Strategies

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#440]
### Description

This issue focuses on documenting the checklist item: Testing Strategies for the project. The checklist will outline key tasks, deliverables, and documentation required for the successful completion of this item. Once created, the checklist will be used to track progress and ensure all necessary steps are completed.

### Required Activities

- [x] Create a checklist for testing strategies, including unit, integration, and end-to-end testing.  
- [x] Include details on testing tools and frameworks to be used.  
- [x] Document the checklist in the Lab8 Pull Request

### Estimated Time

2 hours

### Deadline

03.12.2024

### Reviewer

@cemgungor1

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created the testing strategies documentation part and commented on pr, once this lab concludes this issue will be resolved. Up for rev @cemgungor1 
See [comment](https://github.com/bounswe/bounswe2024group2/pull/434#issuecomment-2514512440)

**Comment by cemgungor1** [comment]
Your documentation looks great. Well done guys. I am closing this issue
