### ISSUE TITLE
Create Wiki for Researches About Wikidata, Linked Data, SPARQL semantic queries, Wikidata API - Furkan Şenkal

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#50]
Create the wiki page for researches about Wikidata, Linked Data, SPARQL semantic queries, and Wikidata API based on the documents provided by responsible team members.

### Tasks to do: 

- [x] Wiki page initialized
- [x] Wikidata API research notes written and shared by @danzio19
- [x] SPARQL Semantic Queries research notes written and shared by @m-erkam
- [x] Linked Data research notes written and shared by @mahmutbugramert 
- [x] Wikidata research notes written and shared by @rukiyeaslan
- [x] Wiki page created and accessible via sidebar

**Comment by furkansenkal** [comment]
All the required tasks are done. Closing the issue.
