### ISSUE TITLE
Update Milestone Report 1 for Individual Contribution

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#84]
- [ ] **Compile a Team Contribution Table**
  - Each team member should document their specific contributions to the project.
  - [x] Yasin Bastug
  - [x] Rukiye Aslan
  - [x] Muhammed Erkam
  - [ ] Kamil Deniz
  - [x] Furkan Senkal
  - [x] Mahmut Buğra
  - [x] Halil Ibrahim Kasapoglu
  - [x] İrem Nur Yıldırım

**Comment by mahmutbugramert** [comment]
Added my personal contribution.

**Comment by rukiyeaslan** [comment]
I added my personal contribution, the updated contribution table can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Milestone-1-Report/26edd495df2fa36a6d8b583eacf70b2b3771c54f).

**Comment by m-erkam** [comment]
Added my personal contribution.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Added my personal contribution to the milestone report, see [here](https://github.com/bounswe/bounswe2024group2/wiki/Milestone-1-Report/24b611b5f3711741e7f61ac231f3d5ba2fd867ed).

**Comment by iremnuy** [comment]
I added my contribution to the report.

**Comment by yasinbastug** [comment]
I also added my contribution and I am closing this issue since Milestone 1 deadline is due.
